# -*- coding: utf-8 -*-
from PyFlow import getRawNodeInstance
# This file was auto-generated by PyFlow exporter 'Graph script v1.0.0'
#	Created: 01:50PM on August 24, 2023

EXPORTER_NAME = 'Graph script'
EXPORTER_VERSION = '1.0.0'

def createScene(ROOT_GRAPH=None):
	randint = getRawNodeInstance('randint', packageName='PyFlowBase', libName='RandomLib')
	ROOT_GRAPH.addNode(randint)
	randint.setPosition(-456.96610169491476, -206.3559322033898)
	randint.setName('randint')
	randint['start'].setData(0)
	randint['end'].setData(5)
	randint['Result'].setData(0)
	delay = getRawNodeInstance('delay', packageName='PyFlowBase', libName=None)
	ROOT_GRAPH.addNode(delay)
	delay.setPosition(-326.0847457627116, -276.1525423728815)
	delay.setName('delay')
	delay['inExec'].setData(None)
	delay['Delay(s)'].setData(0.0)
	delay['outExec'].setData(None)
	doN = getRawNodeInstance('doN', packageName='PyFlowBase', libName=None)
	ROOT_GRAPH.addNode(doN)
	doN.setPosition(-474.49152542372894, -313.49152542372883)
	doN.setName('doN')
	doN['Enter'].setData(None)
	doN['N'].setData(3)
	doN['Reset'].setData(None)
	doN['Exit'].setData(None)
	doN['Counter'].setData(3)
	imageDisplay = getRawNodeInstance('imageDisplay', packageName='PyFlowBase', libName=None)
	ROOT_GRAPH.addNode(imageDisplay)
	imageDisplay.setPosition(-168.0169491525424, -338.3496503496504)
	imageDisplay.setName('imageDisplay')
	imageDisplay['path'].setData('D:\VS_code\PyFlow\PyFlow\UI\resources\binocular.png')
	imageDisplay['inExec'].setData(None)
	imageDisplay['failed'].setData(None)
	imageDisplay['outExec'].setData(None)
	normpath = getRawNodeInstance('normpath', packageName='PyFlowBase', libName='PathLib')
	ROOT_GRAPH.addNode(normpath)
	normpath.setPosition(-300.9244755244755, -179.10069930069932)
	normpath.setName('normpath')
	normpath['path'].setData('D:\VS_code\PyFlow\PyFlow\UI\resources')
	normpath['out'].setData('D:\VS_code\PyFlow\PyFlow\UI\resources')
	add = getRawNodeInstance('add', packageName='PyFlowBase', libName='MathAbstractLib')
	ROOT_GRAPH.addNode(add)
	add.setPosition(-231.46433566433566, -133.5454545454545)
	add.setName('add')
	add['a'].setData('D:\VS_code\PyFlow\PyFlow\UI\resources')
	add['b'].setData('\binocular.png')
	add['out'].setData('D:\VS_code\PyFlow\PyFlow\UI\resources\binocular.png')
	makeString = getRawNodeInstance('makeString', packageName='PyFlowBase', libName='DefaultLib')
	ROOT_GRAPH.addNode(makeString)
	makeString.setPosition(-384.62123300480187, -108.04246525406745)
	makeString.setName('makeString')
	makeString['s'].setData('\binocular.png')
	makeString['out'].setData('\binocular.png')
	
	# connect pins
	

